/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.geonorte.vista;

import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author FP DAM
 */
public class ClienteJFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form JFrameFormularioCliente
     */
    public ClienteJFrame() {
        initComponents();  
        
        setTitle("Area cliente");
        setSize(1000,600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        
        setLocationRelativeTo(null);   
    }

    public JPanel getPanelPantalla() {
        return PanelPantalla;
    }

    public JButton getjButtonAtras() {
        return jButtonAtras;
    }

    public JButton getjButtonBorrarCliente() {
        return jButtonBorrarCliente;
    }

    public JButton getjButtonConsultarCliente() {
        return jButtonConsultarCliente;
    }

    public JButton getjButtonModificarCliente() {
        return jButtonModificarCliente;
    }

    public JButton getjButtonNuevoCliente() {
        return jButtonNuevoCliente;
    }

    public JButton getjButtonSalir() {
        return jButtonSalir;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAbajo = new javax.swing.JPanel();
        jButtonAtras = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelBotones = new javax.swing.JPanel();
        jButtonNuevoCliente = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jButtonModificarCliente = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jButtonConsultarCliente = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jButtonBorrarCliente = new javax.swing.JButton();
        PanelPantalla = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));

        jPanelTitulo.setBackground(new java.awt.Color(35, 120, 125));
        jPanelTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));

        jLabel1.setBackground(new java.awt.Color(225, 235, 237));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(225, 235, 237));
        jLabel1.setText("Área clientes");
        jPanelTitulo.add(jLabel1);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.PAGE_START);

        jPanelAbajo.setBackground(new java.awt.Color(35, 120, 125));
        jPanelAbajo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelAbajo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonAtras.setBackground(new java.awt.Color(225, 235, 237));
        jButtonAtras.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(0, 51, 51));
        jButtonAtras.setText("Menú");
        jPanelAbajo.add(jButtonAtras);

        jButtonSalir.setBackground(new java.awt.Color(225, 235, 237));
        jButtonSalir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(0, 51, 51));
        jButtonSalir.setText("Salir");
        jPanelAbajo.add(jButtonSalir);

        getContentPane().add(jPanelAbajo, java.awt.BorderLayout.PAGE_END);

        jPanelBotones.setBackground(new java.awt.Color(35, 120, 125));
        jPanelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelBotones.setLayout(new javax.swing.BoxLayout(jPanelBotones, javax.swing.BoxLayout.Y_AXIS));

        jButtonNuevoCliente.setBackground(new java.awt.Color(225, 235, 237));
        jButtonNuevoCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonNuevoCliente.setForeground(new java.awt.Color(0, 51, 51));
        jButtonNuevoCliente.setText("Nuevo cliente");
        jButtonNuevoCliente.setMaximumSize(new java.awt.Dimension(120, 60));
        jButtonNuevoCliente.setMinimumSize(new java.awt.Dimension(120, 60));
        jButtonNuevoCliente.setPreferredSize(new java.awt.Dimension(120, 60));
        jPanelBotones.add(jButtonNuevoCliente);
        jPanelBotones.add(filler3);

        jButtonModificarCliente.setBackground(new java.awt.Color(225, 235, 237));
        jButtonModificarCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonModificarCliente.setForeground(new java.awt.Color(0, 51, 51));
        jButtonModificarCliente.setText("Modificar");
        jButtonModificarCliente.setMaximumSize(new java.awt.Dimension(120, 60));
        jButtonModificarCliente.setMinimumSize(new java.awt.Dimension(120, 60));
        jButtonModificarCliente.setPreferredSize(new java.awt.Dimension(120, 60));
        jPanelBotones.add(jButtonModificarCliente);
        jPanelBotones.add(filler1);

        jButtonConsultarCliente.setBackground(new java.awt.Color(225, 235, 237));
        jButtonConsultarCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonConsultarCliente.setForeground(new java.awt.Color(0, 51, 51));
        jButtonConsultarCliente.setText("Consultar");
        jButtonConsultarCliente.setMaximumSize(new java.awt.Dimension(120, 60));
        jButtonConsultarCliente.setMinimumSize(new java.awt.Dimension(120, 60));
        jButtonConsultarCliente.setPreferredSize(new java.awt.Dimension(120, 60));
        jPanelBotones.add(jButtonConsultarCliente);
        jPanelBotones.add(filler2);

        jButtonBorrarCliente.setBackground(new java.awt.Color(225, 235, 237));
        jButtonBorrarCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonBorrarCliente.setForeground(new java.awt.Color(0, 51, 51));
        jButtonBorrarCliente.setText("Borrar");
        jButtonBorrarCliente.setMaximumSize(new java.awt.Dimension(120, 60));
        jButtonBorrarCliente.setMinimumSize(new java.awt.Dimension(120, 60));
        jButtonBorrarCliente.setPreferredSize(new java.awt.Dimension(120, 60));
        jPanelBotones.add(jButtonBorrarCliente);

        getContentPane().add(jPanelBotones, java.awt.BorderLayout.LINE_END);

        PanelPantalla.setMaximumSize(new java.awt.Dimension(870, 480));
        PanelPantalla.setMinimumSize(new java.awt.Dimension(870, 480));
        PanelPantalla.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelPantalla, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPantalla;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBorrarCliente;
    private javax.swing.JButton jButtonConsultarCliente;
    private javax.swing.JButton jButtonModificarCliente;
    private javax.swing.JButton jButtonNuevoCliente;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAbajo;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelTitulo;
    // End of variables declaration//GEN-END:variables
}
