/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.geonorte.vista;

import javax.swing.JList;

/**
 *
 * @author FP DAM
 */
public class ListaClientesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPanelListaClientes
     */
    public ListaClientesJPanel() {
        initComponents();
        setVisible(true);
    }

    public JList<String> getjList_Clientes() {
        return jList_Clientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Clientes = new javax.swing.JList<>();

        setMaximumSize(new java.awt.Dimension(870, 480));
        setMinimumSize(new java.awt.Dimension(870, 480));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(245, 243, 239));
        jPanel4.setMaximumSize(new java.awt.Dimension(277, 57));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 120, 125));
        jLabel3.setText("Listado clientes");
        jPanel4.add(jLabel3);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(245, 243, 239));
        jPanel5.setForeground(new java.awt.Color(245, 243, 239));
        jPanel5.setToolTipText("");

        jScrollPane2.setBackground(new java.awt.Color(245, 243, 239));
        jScrollPane2.setForeground(new java.awt.Color(245, 243, 239));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(840, 360));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(840, 360));
        jScrollPane2.setName(""); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(840, 360));
        jScrollPane2.setRequestFocusEnabled(false);

        jList_Clientes.setBackground(new java.awt.Color(245, 243, 239));
        jList_Clientes.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jList_Clientes.setForeground(new java.awt.Color(0, 51, 51));
        jList_Clientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_Clientes.setMaximumSize(new java.awt.Dimension(840, 350));
        jList_Clientes.setMinimumSize(new java.awt.Dimension(840, 350));
        jList_Clientes.setName(""); // NOI18N
        jList_Clientes.setPreferredSize(new java.awt.Dimension(840, 350));
        jScrollPane2.setViewportView(jList_Clientes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList_Clientes;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
