/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.geonorte.vista;

import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author FP DAM
 */
public class NuevoClienteJPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConsultaCliente
     */
    public NuevoClienteJPanel() {
        initComponents();
    }

    public JButton getjButtonCancelar() {
        return jButtonCancelar;
    }

    public JButton getjButtonGuardar() {
        return jButtonGuardar;
    }

    public JRadioButton getjRadioButton_EmpresaUnica() {
        return jRadioButton_EmpresaUnica;
    }

    public JRadioButton getjRadioButton_GrupoEmpresas() {
        return jRadioButton_GrupoEmpresas;
    }

    public JTextField getjTextField_Calle() {
        return jTextField_Calle;
    }

    public JTextField getjTextField_ID() {
        return jTextField_ID;
    }

    public JTextField getjTextField_Localidad() {
        return jTextField_Localidad;
    }

    public JTextField getjTextField_Numero() {
        return jTextField_Numero;
    }

    public JTextField getjTextField_RazonSocial() {
        return jTextField_RazonSocial;
    }

    public JTextField getjTextField_TipoEmpresa() {
        return jTextField_TipoEmpresa;
    }

    public JTextField getjTextField_cp() {
        return jTextField_cp;
    }

    public JTextField getjTextField_nif() {
        return jTextField_nif;
    }

    public JTextField getjTextField_telefono() {
        return jTextField_telefono;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelIzq = new javax.swing.JPanel();
        jPanelDer = new javax.swing.JPanel();
        jPanelArr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAbj = new javax.swing.JPanel();
        jButtonGuardar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButtonCancelar = new javax.swing.JButton();
        jPanelCen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_EmpresaUnica = new javax.swing.JRadioButton();
        jRadioButton_GrupoEmpresas = new javax.swing.JRadioButton();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_nif = new javax.swing.JTextField();
        jTextField_RazonSocial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_TipoEmpresa = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();
        jTextField_Localidad = new javax.swing.JTextField();
        jTextField_Numero = new javax.swing.JTextField();
        jTextField_Calle = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_cp = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(885, 466));
        setMinimumSize(new java.awt.Dimension(885, 466));
        setPreferredSize(new java.awt.Dimension(885, 466));
        setLayout(new java.awt.BorderLayout());

        jPanelIzq.setBackground(new java.awt.Color(245, 243, 239));

        javax.swing.GroupLayout jPanelIzqLayout = new javax.swing.GroupLayout(jPanelIzq);
        jPanelIzq.setLayout(jPanelIzqLayout);
        jPanelIzqLayout.setHorizontalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelIzqLayout.setVerticalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        add(jPanelIzq, java.awt.BorderLayout.LINE_START);

        jPanelDer.setBackground(new java.awt.Color(245, 243, 239));

        javax.swing.GroupLayout jPanelDerLayout = new javax.swing.GroupLayout(jPanelDer);
        jPanelDer.setLayout(jPanelDerLayout);
        jPanelDerLayout.setHorizontalGroup(
            jPanelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelDerLayout.setVerticalGroup(
            jPanelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        add(jPanelDer, java.awt.BorderLayout.LINE_END);

        jPanelArr.setBackground(new java.awt.Color(245, 243, 239));
        jPanelArr.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 1, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 120, 125));
        jLabel1.setText("Nuevo registro");
        jPanelArr.add(jLabel1);

        add(jPanelArr, java.awt.BorderLayout.PAGE_START);

        jPanelAbj.setBackground(new java.awt.Color(245, 243, 239));
        jPanelAbj.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 20, 1));

        jButtonGuardar.setBackground(new java.awt.Color(35, 120, 125));
        jButtonGuardar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(225, 235, 237));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanelAbj.add(jButtonGuardar);
        jPanelAbj.add(filler1);

        jButtonCancelar.setBackground(new java.awt.Color(35, 120, 125));
        jButtonCancelar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(225, 235, 237));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanelAbj.add(jButtonCancelar);

        add(jPanelAbj, java.awt.BorderLayout.PAGE_END);

        jPanelCen.setBackground(new java.awt.Color(245, 243, 239));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Tipo de entidad:");

        jRadioButton_EmpresaUnica.setBackground(new java.awt.Color(245, 243, 239));
        buttonGroup1.add(jRadioButton_EmpresaUnica);
        jRadioButton_EmpresaUnica.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButton_EmpresaUnica.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButton_EmpresaUnica.setText("Empresa única");
        jRadioButton_EmpresaUnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EmpresaUnicaActionPerformed(evt);
            }
        });

        jRadioButton_GrupoEmpresas.setBackground(new java.awt.Color(245, 243, 239));
        buttonGroup1.add(jRadioButton_GrupoEmpresas);
        jRadioButton_GrupoEmpresas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButton_GrupoEmpresas.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButton_GrupoEmpresas.setText("Grupo empresas");

        jTextField_ID.setMaximumSize(new java.awt.Dimension(269, 22));
        jTextField_ID.setMinimumSize(new java.awt.Dimension(269, 22));
        jTextField_ID.setPreferredSize(new java.awt.Dimension(269, 22));
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });

        jTextField_nif.setMaximumSize(new java.awt.Dimension(269, 22));
        jTextField_nif.setMinimumSize(new java.awt.Dimension(269, 22));
        jTextField_nif.setPreferredSize(new java.awt.Dimension(269, 22));

        jTextField_RazonSocial.setMaximumSize(new java.awt.Dimension(269, 22));
        jTextField_RazonSocial.setMinimumSize(new java.awt.Dimension(269, 22));
        jTextField_RazonSocial.setPreferredSize(new java.awt.Dimension(269, 22));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Razón social:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("NIF");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("ID:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Dirección:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("      Calle:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("      Número:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("     Localidad:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Teléfono:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Tipo empresa:");

        jTextField_TipoEmpresa.setMaximumSize(new java.awt.Dimension(269, 22));
        jTextField_TipoEmpresa.setMinimumSize(new java.awt.Dimension(269, 22));
        jTextField_TipoEmpresa.setPreferredSize(new java.awt.Dimension(269, 22));

        jTextField_telefono.setMaximumSize(new java.awt.Dimension(269, 22));
        jTextField_telefono.setMinimumSize(new java.awt.Dimension(269, 22));
        jTextField_telefono.setPreferredSize(new java.awt.Dimension(269, 22));

        jTextField_Localidad.setPreferredSize(new java.awt.Dimension(269, 22));

        jTextField_Calle.setPreferredSize(new java.awt.Dimension(269, 22));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("CP:");

        javax.swing.GroupLayout jPanelCenLayout = new javax.swing.GroupLayout(jPanelCen);
        jPanelCen.setLayout(jPanelCenLayout);
        jPanelCenLayout.setHorizontalGroup(
            jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCenLayout.createSequentialGroup()
                        .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_RazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelCenLayout.createSequentialGroup()
                                .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_TipoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelCenLayout.createSequentialGroup()
                                        .addComponent(jRadioButton_EmpresaUnica)
                                        .addGap(26, 26, 26)
                                        .addComponent(jRadioButton_GrupoEmpresas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCenLayout.createSequentialGroup()
                                        .addComponent(jTextField_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_Localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_Calle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(58, 58, 58))
                    .addGroup(jPanelCenLayout.createSequentialGroup()
                        .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCenLayout.setVerticalGroup(
            jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_EmpresaUnica)
                    .addComponent(jRadioButton_GrupoEmpresas)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_RazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        add(jPanelCen, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_EmpresaUnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EmpresaUnicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_EmpresaUnicaActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAbj;
    private javax.swing.JPanel jPanelArr;
    private javax.swing.JPanel jPanelCen;
    private javax.swing.JPanel jPanelDer;
    private javax.swing.JPanel jPanelIzq;
    private javax.swing.JRadioButton jRadioButton_EmpresaUnica;
    private javax.swing.JRadioButton jRadioButton_GrupoEmpresas;
    private javax.swing.JTextField jTextField_Calle;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Localidad;
    private javax.swing.JTextField jTextField_Numero;
    private javax.swing.JTextField jTextField_RazonSocial;
    private javax.swing.JTextField jTextField_TipoEmpresa;
    private javax.swing.JTextField jTextField_cp;
    private javax.swing.JTextField jTextField_nif;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
